from building import *
import os

cwd     = GetCurrentDir()
CPPPATH = [cwd]
src     = ['main.c']

# USB test app is only compiled when the matching cherryusb device
# template is enabled in menuconfig (rtconfig.h).
if GetDepend(['RT_CHERRYUSB_DEVICE_TEMPLATE_HID_KEYBOARD']):
    src += ['usb_hid_keyboard.c']

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

list = os.listdir(cwd)
for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        group = group + SConscript(os.path.join(item, 'SConscript'))

Return('group')
